# Generated by Django 4.1 on 2024-06-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstallType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('remote', 'Remote'), ('local', 'Local')], max_length=10)),
            ],
        ),
    ]
